title: "My Work Log"
description: "UFS 4.0 최적화 공부 기록"
theme: jekyll-theme-minimal   # 가장 가벼운 기본 테마
permalink: /:title/           # URL을 깔끔하게

collections:
  ufs4:                # 컬렉션 이름 (앞으로 'site.ufs4' 로 접근)
    output: true       # HTML로 빌드해서 주소에 노출
    permalink: /ufs4/:path/   # 최종 URL 패턴
