title: "My Work Log"
description: "UFS 4.0 최적화 공부 기록"
theme: jekyll-theme-minimal   # 가장 가벼운 기본 테마
permalink: /:title/           # URL을 깔끔하게

collections:
  ufs4:
    output: true
    permalink: /ufs4/:path/

  linux6646:           # ← 새 컬렉션 키
    output: true
    permalink: /linux-v6.6.46/:path/
